"""Initial migration

Revision ID: a80f8755ec2f
Revises: 
Create Date: 2024-12-23 14:18:20.184162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80f8755ec2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chapters',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('workers_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.role_id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['Titles.title_id'], ),
    sa.ForeignKeyConstraint(['workers_id'], ['Workers.workers_id'], ),
    sa.PrimaryKeyConstraint('chapter_id'),
    sa.UniqueConstraint('chapter_id')
    )
    op.create_table('Roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('role_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_id')
    )
    op.create_table('Titles',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('ru_name', sa.String(), nullable=False),
    sa.Column('en_name', sa.String(), nullable=True),
    sa.Column('jp_name', sa.String(), nullable=True),
    sa.Column('last_chapter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_chapter'], ['Chapters.chapter_id'], ),
    sa.PrimaryKeyConstraint('title_id'),
    sa.UniqueConstraint('title_id')
    )
    op.create_table('Workers',
    sa.Column('workers_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('discord_access_token', sa.String(), nullable=False),
    sa.Column('discord_refresh_token', sa.String(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('last_upload', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('workers_id'),
    sa.UniqueConstraint('discord_id'),
    sa.UniqueConstraint('workers_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Workers')
    op.drop_table('Titles')
    op.drop_table('Roles')
    op.drop_table('Chapters')
    # ### end Alembic commands ###
